### ISSUE TITLE
ROS2 Eloquent Upgrade

### ISSUE THREAD

**Issue by stonier** [kobuki-base/velocity_smoother#2]
* [x] upgrade codebase to ROS2 &rarr; PR #1
* [x] switch to the devel/release branching convention used in this organisation
* [x] bump minor (major?) version: `0.13.0` - it's not stable-worthy yet
* [x] bloom-release, with PR hooks (test & confirm), https://github.com/ros/rosdistro/pull/23549
* [x] upgrade test (make sure we have a library test and an integration test), #5 &rarr; PR #7
* [x] LICENSE off to a branch and update links &rarr; PR #3
* [x] more obvious parameter / topic names, &rarr; PR #8
* [x] create README with instructions (replacing the wiki, discoverable by rosindex), &rarr; PR #8

**Comment by stonier** [comment]
FYI @clalancette releasing `v0.14.0`
